name: Maven Build (9 Goals)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Show files (Debug)
        run: |
          pwd
          ls -la

      - name: Maven Version
        run: mvn -v

      - name: 1) validate
        run: mvn validate

      - name: 2) compile
        run: mvn compile

      - name: 3) test
        run: mvn test

      - name: 4) package
        run: mvn package

      - name: 5) verify
        run: mvn verify

      - name: 6) install
        run: mvn install

      - name: 7) site
        run: mvn site

      - name: 8) clean
        run: mvn clean

      - name: 9) deploy (optional)
        run: mvn deploy
        continue-on-error: true
